# Creating matrices in python using numpy

In [1]:
import numpy as np
streetlights = np.array([[ 1, 0, 1 ],
                         [ 0, 1, 1 ],
                         [ 0, 0, 1 ],
                         [ 1, 1, 1 ],
                         [ 0, 1, 1 ],
                         [ 1, 0, 1 ] ] )

In [9]:
streetlights[0].shape

(3,)

In [6]:
walk_vs_stop = np.array([ [ 0 ],
                             [ 1 ],
                             [ 0 ],
                             [ 1 ],
                             [ 1 ],
                             [ 0 ] ])

In [8]:
walk_vs_stop.shape
import numpy as np

## Using the above example for prediction

In [15]:
import numpy as np
streetlights = np.array([[ 1, 0, 1 ],
                         [ 0, 1, 1 ],
                         [ 0, 0, 1 ],
                         [ 1, 1, 1 ],
                         [ 0, 1, 1 ],
                         [ 1, 0, 1 ] ] )
walk_vs_stop = np.array([0,1,0,1,1,0])

input = streetlights[0]
output = walk_vs_stop[0]

iterations = 100
alpha =0.1
weights = np.random.rand(3)
print(weights)
def w_sum(a,b):
    assert(len(a)==len(b))
    out = 0
    for i in range(len(a)):
        out += a[i]*b[i]
    return out

def scalar_ele_mul(a,b):
    out = []
    for i in range(len(a)):
        out.append(a[i]*b)
    return out

def neural_network(input,weights):
    pred = w_sum(input,weights)
    return pred

for k in range(iterations):
    pred = neural_network(input,weights)
    error = (pred - output)**2
    delta = (pred-output)
    weight_delta = scalar_ele_mul(input,delta)
    
    for i in range(len(weights)):
        weights[i] -= weight_delta[i]*alpha
    print('Iteration {} Prediction {} actual {}'.format(k+1,pred,output))


[0.02037538 0.08758516 0.95903541]
Iteration 1 Prediction 0.979410781472529 actual 0
Iteration 2 Prediction 0.7835286251780231 actual 0
Iteration 3 Prediction 0.6268229001424186 actual 0
Iteration 4 Prediction 0.5014583201139349 actual 0
Iteration 5 Prediction 0.40116665609114793 actual 0
Iteration 6 Prediction 0.32093332487291837 actual 0
Iteration 7 Prediction 0.2567466598983347 actual 0
Iteration 8 Prediction 0.20539732791866772 actual 0
Iteration 9 Prediction 0.16431786233493412 actual 0
Iteration 10 Prediction 0.13145428986794733 actual 0
Iteration 11 Prediction 0.1051634318943579 actual 0
Iteration 12 Prediction 0.08413074551548627 actual 0
Iteration 13 Prediction 0.06730459641238906 actual 0
Iteration 14 Prediction 0.05384367712991123 actual 0
Iteration 15 Prediction 0.043074941703929004 actual 0
Iteration 16 Prediction 0.034459953363143225 actual 0
Iteration 17 Prediction 0.027567962690514536 actual 0
Iteration 18 Prediction 0.02205437015241163 actual 0
Iteration 19 Prediction 

## Simpler version of the above

In [19]:
import numpy as np
streetlights = np.array([[ 1, 0, 1 ],
                         [ 0, 1, 1 ],
                         [ 0, 0, 1 ],
                         [ 1, 1, 1 ],
                         [ 0, 1, 1 ],
                         [ 1, 0, 1 ] ] )
walk_vs_stop = np.array([0,1,0,1,1,0])

input = streetlights[0]
output = walk_vs_stop[0]

iterations = 100
alpha =0.1
weights = np.random.rand(3)

for i in range(iterations):
    pred = input.dot(weights)
    error = (pred - output)**2
    weights -= (input*(pred-output)*alpha)
    print('iteration {} predictions {} actual {} error {}'.format(i+1,pred,output,error))

iteration 1 predictions 1.2488007919132569 actual 0 error 1.5595034178831775
iteration 2 predictions 0.9990406335306056 actual 0 error 0.9980821874452337
iteration 3 predictions 0.7992325068244844 actual 0 error 0.6387725999649495
iteration 4 predictions 0.6393860054595876 actual 0 error 0.40881446397756777
iteration 5 predictions 0.51150880436767 actual 0 error 0.2616412569456433
iteration 6 predictions 0.40920704349413595 actual 0 error 0.16745040444521167
iteration 7 predictions 0.3273656347953088 actual 0 error 0.10716825884493549
iteration 8 predictions 0.26189250783624707 actual 0 error 0.06858768566075873
iteration 9 predictions 0.20951400626899763 actual 0 error 0.04389611882288558
iteration 10 predictions 0.1676112050151981 actual 0 error 0.028093516046646772
iteration 11 predictions 0.1340889640121585 actual 0 error 0.017979850269853936
iteration 12 predictions 0.10727117120972682 actual 0 error 0.011507104172706523
iteration 13 predictions 0.08581693696778145 actual 0 error 

# predicting using multiple training samples 

In [78]:
import numpy as np
streetlights = np.array([[ 1, 0, 1 ],
                         [ 0, 1, 1 ],
                         [ 0, 0, 1 ],
                         [ 1, 1, 1 ],
                         [ 0, 1, 1 ],
                         [ 1, 0, 1 ] ] )
walk_vs_stop = np.array([0,1,0,1,1,0])

#input = streetlights[0]
#output = walk_vs_stop[0]

iterations = 100
alpha =0.01
weights = np.random.rand(3)

for i in range(iterations):
    total_error= 0
    for j in range(len(walk_vs_stop)):
        input = streetlights[j]
        output = walk_vs_stop[j]
        
        pred = input.dot(weights)
        error = (pred - output)**2
        total_error += error
        weights -= (alpha*input*(pred-output))
    print('iteration {} total_error {}'.format(i+1,total_error))

iteration 1 total_error 1.6736011359067322
iteration 2 total_error 1.6040803473166094
iteration 3 total_error 1.5379246969053622
iteration 4 total_error 1.474894683512242
iteration 5 total_error 1.4147786212389377
iteration 6 total_error 1.3573883765062424
iteration 7 total_error 1.3025558191501219
iteration 8 total_error 1.2501298652508073
iteration 9 total_error 1.1999740104485364
iteration 10 total_error 1.1519642699287784
iteration 11 total_error 1.1059874556844322
iteration 12 total_error 1.0619397336005956
iteration 13 total_error 1.019725412787964
iteration 14 total_error 0.9792559277684467
iteration 15 total_error 0.9404489808849095
iteration 16 total_error 0.9032278179090254
iteration 17 total_error 0.8675206144581243
iteration 18 total_error 0.8332599546701203
iteration 19 total_error 0.800382386762745
iteration 20 total_error 0.768828042733418
iteration 21 total_error 0.7385403116334275
iteration 22 total_error 0.7094655576527543
iteration 23 total_error 0.681552875744403
it

In [76]:
test = np.array([0,1,1])
prediction = test.dot(weights)
print(prediction)
if prediction > 0.5:
    prediction = 1
else:
    prediction = 0
print(prediction)

0.9999808591468631
1


In [77]:
weights

array([ 1.55354099e-04,  1.00015536e+00, -1.74497723e-04])

In [72]:
import numpy as np
streetlights = np.array([[ 0.999, 0.001, 0.999 ],
                         [ 0, 0.999, 0.999 ],
                         [ 0, 0.001, 0.999 ],
                         [ 0.999, 0.999, 0.999 ],
                         [ 0, 0.999, 0.999 ],
                         [ 0.999, 0.001, 0.999 ] ] )
walk_vs_stop = np.array([0.002,0.98,0.002,1,1,0])

#input = streetlights[0]
#output = walk_vs_stop[0]

iterations = 100
alpha = 0.01
weights = np.random.rand(3)
print(weights)
for i in range(iterations):
    total_error= 0
    for j in range(len(walk_vs_stop)):
        input = streetlights[j]
        output = walk_vs_stop[j]
        
        pred = input.dot(weights)
        error = (pred - output)**2
        total_error += error
        weights -= (alpha*input*(pred-output))
    print('iteration {} total_error {}'.format(i+1,total_error))

[0.78180886 0.25536672 0.6993392 ]
iteration 1 total_error 5.194720027306678
iteration 2 total_error 4.622694404278844
iteration 3 total_error 4.136907571557252
iteration 4 total_error 3.722988283735061
iteration 5 total_error 3.3690210629991064
iteration 6 total_error 3.0651240811313176
iteration 7 total_error 2.8030996973620423
iteration 8 total_error 2.5761451424614483
iteration 9 total_error 2.3786129934722533
iteration 10 total_error 2.205812866599762
iteration 11 total_error 2.053847231850457
iteration 12 total_error 1.919475474917801
iteration 13 total_error 1.8000013433194089
iteration 14 total_error 1.6931797511228575
iteration 15 total_error 1.5971396097494241
iteration 16 total_error 1.5103199261427895
iteration 17 total_error 1.4314168845851287
iteration 18 total_error 1.3593400216490878
iteration 19 total_error 1.2931759292743072
iteration 20 total_error 1.2321581904098926
iteration 21 total_error 1.1756424747204042
iteration 22 total_error 1.1230859065017023
iteration 23 

In [73]:
test = np.array([1,1,1])
prediction = test.dot(weights)
print(prediction)
if prediction > 0.5:
    prediction = 1
else:
    prediction = 0
print(prediction)

0.8916227872714496
1


In [79]:
weights

array([0.0450646 , 0.87549006, 0.04461278])